language: python

install:
  - pip install -r requirements.txt

python:
  - 3.6

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=project_finder.settings

before_script:
  - psql -c "CREATE USER root WITH CREATEUSER PASSWORD 'pass@123';" -U postgres
  - psql -c "ALTER USER root CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE project_finder WITH OWNER root ENCODING 'UTF8';" -U postgres
  - python3 manage.py makemigrations project_finder_web_app
  - python3 manage.py migrate
  - python3 manage.py migrate --run-syncdb

env:
  - DJANGO=2.1.5 DB=postgresql SECRET_KEY='=xti712i87pm=a_wyq$chj8v)zqzzp))q1*5!padcx1yhx=%^)' DEBUG='True' ENGINE='django.db.backends.postgresql_psycopg2' DB_NAME='project_finder' DB_USER='root' DB_PASS='pass@123' DB_HOST='localhost' DB_PORT='5432'

script:
  - flake8
  - python3 manage.py test
